<?php

/**
 * @file
 * Contains mbta_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mbta_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mbta_api module.
    case 'help.page.mbta_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Retrieves and displays data from the MBTA api.') . '</p>';
      return $output;

    default:
  }
}
